config/routes.rb
Purpleline::Application.routes.draw do


  resources :reports

  #get "static_maps/map"

  #get "static_pages/page"
  resources :members
  devise_for :users, :path_names => {:sign_up => "register"}
namespace :admin do
  resources :purple_assets
  resources :profiles
  resources :roles
  resources :newsletters_translations
  resources :categories
  resources :newsletters_types
  resources :newsletters  do resources :purple_assets end
  resources :events_translations
  resources :events_types
  resources :events do resources :purple_assets end
  resources :pages_translations
  resources :pages
  resources :languages
  resources :announces_types  
  resources :announces do resources :purple_assets end
  resources :announces_translations
  resources :tasks
  resources :tasks_translations
  resources :stations do resources :purple_assets end
  resources :stations_translations  
  resources :progresses
  resources :users
  resources :reports
  resources :reports_translations
  resources :reports_types
end

  root :to => "home#index",:lang=>"th"
  get   "/home/allannounce"
  get   "home/lasttenannounce"
  get   "home/monthlyannounce"
  get   "/home/allnews"
  get   "/home/lasttennews"
  get   "/home/monthlynews"
  get   "/home/allreport"
  get   "home/latestreport"
  get   "home/monthlyreport"
  get   "/home/allevent"
  get   "home/latestevent"
  get   "home/monthlyevent"
  get   "home/gallery"   
  get   "home/setlang"
  match "/page/:filename.:format" => "static_pages#page"
  match "/map/:mapname/:filename.:format" => "static_maps#map"
  match "/map/:mapname/:z/:x/:y.:format" => "static_maps#maptile"
  match "/allstation" => "home#allstation"
  match "/main" => "home#index"
  match "/mrta" => "home#mrta"
  match "/gallery" => "home#gallery"
  match "/allannounce" =>  "home#allannounce"
  match "/project" => "home#project"
  match "/station/:id" => 'home#station'
  match "/faceboxmap/:id" => 'home#faceboxmap'
  match "/pagetran/:id" => 'home#pagetran'
  match "/pageview/:id" => 'home#pageview'
  match "/mrtaview/:id" => 'home#mrtaview' 
  match "/category/:id" => 'home#category'   
  match "/eventstype/:id" => 'home#eventstype'   
  match "/reportstype/:id" => 'home#reportstype'   
  
  match "/announce/:id" => 'home#announcement' 
  match "/showevent/:id" => 'home#showevent'   
  match "/showreport/:id" => 'home#showreport'   
  match "/shownews/:id" => 'home#shownews'   
  match "/progress" => 'home#progress'
  match "/filterstation/:id" => 'home#filterstation'
  match "/fullmap" => 'home#fullmap'
  match "/admin" => 'admin/pages#index'

end

app/controllers/admin/reports_types_controller.rb
class Admin::ReportsTypesController < ApplicationController
  layout "admin"
  # GET /reports_types
  # GET /reports_types.xml
  def index
    @reports_types = ReportsType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports_types }
    end
  end

  # GET /reports_types/1
  # GET /reports_types/1.xml
  def show
    @reports_type = ReportsType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reports_type }
    end
  end

  # GET /reports_types/new
  # GET /reports_types/new.xml
  def new
    @reports_type = ReportsType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reports_type }
    end
  end

  # GET /reports_types/1/edit
  def edit
    @reports_type = ReportsType.find(params[:id])
  end

  # POST /reports_types
  # POST /reports_types.xml
  def create
    @reports_type = ReportsType.new(params[:reports_type])

    respond_to do |format|
      if @reports_type.save
        format.html { redirect_to([:admin,@reports_type], :notice => 'Reports type was successfully created.') }
        format.xml  { render :xml => @reports_type, :status => :created, :location => @reports_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reports_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reports_types/1
  # PUT /reports_types/1.xml
  def update
    @reports_type = ReportsType.find(params[:id])

    respond_to do |format|
      if @reports_type.update_attributes(params[:reports_type])
        format.html { redirect_to([:admin,@reports_type], :notice => 'Reports type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reports_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reports_types/1
  # DELETE /reports_types/1.xml
  def destroy
    @reports_type = ReportsType.find(params[:id])
    @reports_type.destroy

    respond_to do |format|
      format.html { redirect_to(admin_reports_types_url) }
      format.xml  { head :ok }
    end
  end

end

app/controllers/reports_types_controller.rb
class ReportsTypesController < ApplicationController
  # GET /reports_types
  # GET /reports_types.xml
  def index
    @reports_types = ReportsType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @reports_types }
    end
  end

  # GET /reports_types/1
  # GET /reports_types/1.xml
  def show
    @reports_type = ReportsType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @reports_type }
    end
  end

  # GET /reports_types/new
  # GET /reports_types/new.xml
  def new
    @reports_type = ReportsType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @reports_type }
    end
  end

  # GET /reports_types/1/edit
  def edit
    @reports_type = ReportsType.find(params[:id])
  end

  # POST /reports_types
  # POST /reports_types.xml
  def create
    @reports_type = ReportsType.new(params[:reports_type])

    respond_to do |format|
      if @reports_type.save
        format.html { redirect_to(@reports_type, :notice => 'Reports type was successfully created.') }
        format.xml  { render :xml => @reports_type, :status => :created, :location => @reports_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @reports_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /reports_types/1
  # PUT /reports_types/1.xml
  def update
    @reports_type = ReportsType.find(params[:id])

    respond_to do |format|
      if @reports_type.update_attributes(params[:reports_type])
        format.html { redirect_to(@reports_type, :notice => 'Reports type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @reports_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reports_types/1
  # DELETE /reports_types/1.xml
  def destroy
    @reports_type = ReportsType.find(params[:id])
    @reports_type.destroy

    respond_to do |format|
      format.html { redirect_to(reports_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/reports_types_helper.rb
module Admin::ReportsTypesHelper
end

app/helpers/reports_types_helper.rb
module ReportsTypesHelper
end

app/views/admin/reports_types/_form.html.erb
  <div class="group">
    <%= f.label :name_th, t("activerecord.attributes.reports_type.name_th", :default => "Name_TH"), :class => :label %>
    <%= f.text_field :name_th, :class => 'text_field' %>

  </div>

  <div class="group">
    <%= f.label :name_en, t("activerecord.attributes.reports_type.name_en", :default => "Name_EN"), :class => :label %>
    <%= f.text_field :name_en, :class => 'text_field' %>

  </div>

 <div class="group">
   <label class="label">Upload icon</label>
   <%=f.file_field  :icon%> 
 </div>    
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>
  <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_reports_types_path, :class => "text_button_padding link_button" %>
</div>

app/views/admin/reports_types/_sidebar.html.erb
<div class="block">
  <h3>Document Categories</h3>
  <ul class="navigation">
    <li><a href="<%= admin_languages_path %>">Languages</a></li>
    <li><a href="<%= admin_pages_path %>">Pages</a></li>
    <li><a href="<%= admin_stations_path %>">Stations</a></li>
    <li><a href="<%= admin_tasks_path %>">Tasks</a></li>
    <li><a href="<%= admin_announces_path %>">Announces</a></li>
    <li><a href="<%= admin_events_path %>">Events</a></li>
    <li><a href="<%= admin_newsletters_path %>">Newletters</a></li> 
    <li><a href="<%= admin_reports_path %>">Reports</a></li> 
  </ul>

  
  <h3>Document Types</h3>
  <ul class="navigation">
    <li><a href="<%= admin_categories_path %>">Categories</a></li>
    <li><a href="<%= admin_events_types_path %>">EventsTypes</a></li>
    <li><a href="<%= admin_newsletters_types_path %>">NewlettersTypes</a></li>  
    <li><a href="<%= admin_reports_types_path %>">ReportsTypes</a></li>  
  </ul>

  <h3>User Management (only Admin)</h3>
  <ul class="navigation">
    <li><a href="<%= admin_users_path %>">User</a></li>
    <li><a href="<%= admin_profiles_path %>">Profile</a></li>
    <li><a href="<%= admin_roles_path %>">Roles Base Authentication</a></li>    
  </ul>
</div>


<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>

app/views/admin/reports_types/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_reports_types_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_reports_type_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_reports_type_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> ReportsType</h2>
    <div class="inner">
      <%= form_for @reports_type, :url => admin_reports_type_path(@reports_type),  :html => {:multipart=>true, :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/reports_types/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_reports_types_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_reports_type_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> ReportsTypes</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.admin_reports_type.name_th", :default => t("activerecord.labels.name_th", :default => "Name_TH")) %>
          </th>
                    <th>
            <%= t("activerecord.attributes.admin_reports_type.name_en", :default => t("activerecord.labels.name_en", :default => "Name_EN")) %>
          </th>          
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @reports_types.each do |reports_type| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= reports_type.id %>
          </td>
          <td>
            <%= link_to reports_type.name_th, admin_reports_type_path(reports_type) %>
          </td>
          <td>
            <%= link_to reports_type.name_en, admin_reports_type_path(reports_type) %>
          </td>          
                    <td>
            <%= reports_type.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_reports_type_path(reports_type) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_reports_type_path(reports_type) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_reports_type_path(reports_type), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/reports_types/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_reports_types_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_reports_type_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  ReportsType</h2>
    <div class="inner">
      <%= form_for :reports_type, :url => admin_reports_types_path, :html => {:multipart=>true, :class => :form }  do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/reports_types/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_reports_types_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_reports_type_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_reports_type_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_reports_type.name_th", :default => t("activerecord.labels.name_th", :default => "Name_TH")) %>:</b>
          <%= @reports_type.name_th %>
        </p>
        <p>
          <b><%= t("activerecord.attributes.admin_reports_type.name_en", :default => t("activerecord.labels.name_en", :default => "Name_EN")) %>:</b>
          <%= @reports_type.name_en %>
        </p>

           <p>icon:
           <%if  @reports_type.icon.exists? then %>
                 <%= image_tag @reports_type.icon.url(:iconsmall) %>
           <%end%>
           </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_reports_type_path(@reports_type), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_reports_type_path(@reports_type), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>