config/routes.rb
Purpleline::Application.routes.draw do


  resources :reports

  #get "static_maps/map"

  #get "static_pages/page"
  resources :members
  devise_for :users, :path_names => {:sign_up => "register"}
namespace :admin do
  resources :purple_assets
  resources :profiles
  resources :roles
  resources :newsletters_translations
  resources :categories
  resources :newsletters_types
  resources :newsletters  do resources :purple_assets end
  resources :events_translations
  resources :events_types
  resources :events do resources :purple_assets end
  resources :pages_translations
  resources :pages
  resources :languages
  resources :announces_types  
  resources :announces do resources :purple_assets end
  resources :announces_translations
  resources :tasks
  resources :tasks_translations
  resources :stations do resources :purple_assets end
  resources :stations_translations  
  resources :progresses
  resources :users
  resources :reports
  resources :reports_translations
  resources :reports_types
end

  root :to => "home#index",:lang=>"th"
  get   "/home/allannounce"
  get   "home/lasttenannounce"
  get   "home/monthlyannounce"
  get   "/home/allnews"
  get   "/home/lasttennews"
  get   "/home/monthlynews"
  get   "/home/allreport"
  get   "home/latestreport"
  get   "home/monthlyreport"
  get   "/home/allevent"
  get   "home/latestevent"
  get   "home/monthlyevent"
  get   "home/gallery"   
  get   "home/setlang"
  match "/page/:filename.:format" => "static_pages#page"
  match "/map/:mapname/:filename.:format" => "static_maps#map"
  match "/map/:mapname/:z/:x/:y.:format" => "static_maps#maptile"
  match "/allstation" => "home#allstation"
  match "/main" => "home#index"
  match "/mrta" => "home#mrta"
  match "/gallery" => "home#gallery"
  match "/allannounce" =>  "home#allannounce"
  match "/project" => "home#project"
  match "/station/:id" => 'home#station'
  match "/faceboxmap/:id" => 'home#faceboxmap'
  match "/pagetran/:id" => 'home#pagetran'
  match "/pageview/:id" => 'home#pageview'
  match "/mrtaview/:id" => 'home#mrtaview' 
  match "/category/:id" => 'home#category'   
  match "/eventstype/:id" => 'home#eventstype'   
  match "/reportstype/:id" => 'home#reportstype'   
  
  match "/announce/:id" => 'home#announcement' 
  match "/showevent/:id" => 'home#showevent'   
  match "/showreport/:id" => 'home#showreport'   
  match "/shownews/:id" => 'home#shownews'   
  match "/progress" => 'home#progress'
  match "/filterstation/:id" => 'home#filterstation'
  match "/fullmap" => 'home#fullmap'
  match "/admin" => 'admin/pages#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  cattr_reader :per_page
  has_many  :events_translations
  @@per_page = 10	
  has_many  :purple_assets, :as => :attachable
  has_and_belongs_to_many :events_types
end

app/models/event/image.rb
class Event::Image < PurpleAsset
  has_attached_file :attachment,  :url => "/:class/:attachment/:id/:style_:basename.:extension",
         :styles => { :small => "200x150>", :middle => "400x300>" ,:large => "800x600>" }	
end

app/models/events_type.rb
class EventsType < ActiveRecord::Base
  has_and_belongs_to_many :events
   has_attached_file  :icon, :styles => {:iconsmall=>"32x32>"},
  :url  => "/icons/:id/:style/:basename.:extension",
  :path => ":rails_root/public/icons/:id/:style/:basename.:extension", :dependent => :destroy
  validates_attachment_content_type :icon, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
	layout "admin"
	before_filter :authenticate_user!	
  # GET /events
  # GET /events.xml
  def index
  	page = params[:page] || 1  	
    @events = Event.paginate :page => page, :order => 'created_at DESC'

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to([:admin,@event], :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to([:admin,@event], :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(admin_events_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	layout "admin"
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.event.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :cache_slug, t("activerecord.attributes.event.cache_slug", :default => "Cache slug"), :class => :label %>
    <%= f.text_field :cache_slug, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

<% for eventcategory in EventsType.all %>
  <%= check_box_tag "event[events_type_ids][]", eventcategory.id, @event.events_types.include?(eventcategory) %>
  <%= eventcategory.name_en %>
<% end %>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
  <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + " " + t("web-app-theme.cancel", :default => "Cancel"), admin_events_path, :class => "button" %> 
</div>

app/views/admin/events/_sidebar.html.erb
<div class="block">
  <h3>Document Categories</h3>
  <ul class="navigation">
    <li><a href="<%= admin_languages_path %>">Languages</a></li>
    <li><a href="<%= admin_pages_path %>">Pages</a></li>
    <li><a href="<%= admin_stations_path %>">Stations</a></li>
    <li><a href="<%= admin_tasks_path %>">Tasks</a></li>
    <li><a href="<%= admin_announces_path %>">Announces</a></li>
    <li><a href="<%= admin_events_path %>">Events</a></li>
    <li><a href="<%= admin_newsletters_path %>">Newletters</a></li> 
    <li><a href="<%= admin_reports_path %>">Reports</a></li> 
  </ul>

  
  <h3>Document Types</h3>
  <ul class="navigation">
    <li><a href="<%= admin_categories_path %>">Categories</a></li>
    <li><a href="<%= admin_events_types_path %>">EventsTypes</a></li>
    <li><a href="<%= admin_newsletters_types_path %>">NewlettersTypes</a></li>  
    <li><a href="<%= admin_reports_types_path %>">ReportsTypes</a></li>  
  </ul>

  <h3>User Management (only Admin)</h3>
  <ul class="navigation">
    <li><a href="<%= admin_users_path %>">User</a></li>
    <li><a href="<%= admin_profiles_path %>">Profile</a></li>
    <li><a href="<%= admin_roles_path %>">Roles Base Authentication</a></li>    
  </ul>
</div>


<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>

app/views/admin/events/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_events_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_event_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_event_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Event</h2>
    <div class="inner">
      <%= form_for @event, :url => admin_event_path(@event), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/events/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_events_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_event_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Events</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
                    <th>
            <%= t("activerecord.attributes.admin_event.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @events.each do |event| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= event.id %>
          </td>
                    <td>
            <%= link_to event.name, admin_event_path(event) %>
          </td>
                    <td>
            <%= event.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_event_path(event) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_event_path(event) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_event_path(event), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @events  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/events/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_events_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_event_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Event</h2>
    <div class="inner">
      <%= form_for :event, :url => admin_events_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/events/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_events_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_event_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_event_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_event.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @event.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_event.cache_slug", :default => t("activerecord.labels.cache_slug", :default => "Cache slug")) %>:</b>
          <%= @event.cache_slug %>
        </p>
        
        <div  class="">
        <b>In Categories: </b>
        <% @event.events_type_ids.each do |id| %>
           <%=EventsType.where("id=?",id).first.name_en%>,
        <%end%>
        </div>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_event_path(@event), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_event_path(@event), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>