config/routes.rb
Purpleline::Application.routes.draw do


  resources :reports

  #get "static_maps/map"

  #get "static_pages/page"
  resources :members
  devise_for :users, :path_names => {:sign_up => "register"}
namespace :admin do
  resources :purple_assets
  resources :profiles
  resources :roles
  resources :newsletters_translations
  resources :categories
  resources :newsletters_types
  resources :newsletters  do resources :purple_assets end
  resources :events_translations
  resources :events_types
  resources :events do resources :purple_assets end
  resources :pages_translations
  resources :pages
  resources :languages
  resources :announces_types  
  resources :announces do resources :purple_assets end
  resources :announces_translations
  resources :tasks
  resources :tasks_translations
  resources :stations do resources :purple_assets end
  resources :stations_translations  
  resources :progresses
  resources :users
  resources :reports
  resources :reports_translations
  resources :reports_types
end

  root :to => "home#index",:lang=>"th"
  get   "/home/allannounce"
  get   "home/lasttenannounce"
  get   "home/monthlyannounce"
  get   "/home/allnews"
  get   "/home/lasttennews"
  get   "/home/monthlynews"
  get   "/home/allreport"
  get   "home/latestreport"
  get   "home/monthlyreport"
  get   "/home/allevent"
  get   "home/latestevent"
  get   "home/monthlyevent"
  get   "home/gallery"   
  get   "home/setlang"
  match "/page/:filename.:format" => "static_pages#page"
  match "/map/:mapname/:filename.:format" => "static_maps#map"
  match "/map/:mapname/:z/:x/:y.:format" => "static_maps#maptile"
  match "/allstation" => "home#allstation"
  match "/main" => "home#index"
  match "/mrta" => "home#mrta"
  match "/gallery" => "home#gallery"
  match "/allannounce" =>  "home#allannounce"
  match "/project" => "home#project"
  match "/station/:id" => 'home#station'
  match "/faceboxmap/:id" => 'home#faceboxmap'
  match "/pagetran/:id" => 'home#pagetran'
  match "/pageview/:id" => 'home#pageview'
  match "/mrtaview/:id" => 'home#mrtaview' 
  match "/category/:id" => 'home#category'   
  match "/eventstype/:id" => 'home#eventstype'   
  match "/reportstype/:id" => 'home#reportstype'   
  
  match "/announce/:id" => 'home#announcement' 
  match "/showevent/:id" => 'home#showevent'   
  match "/showreport/:id" => 'home#showreport'   
  match "/shownews/:id" => 'home#shownews'   
  match "/progress" => 'home#progress'
  match "/filterstation/:id" => 'home#filterstation'
  match "/fullmap" => 'home#fullmap'
  match "/admin" => 'admin/pages#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	belongs_to :company
	has_attached_file  :icon, :styles => {:iconsmall=>"32x32#",:small=>"48x48>",:normal=>"85x85>"},
  :url  => "/avatars/:id/:style/:basename.:extension",
  :path => ":rails_root/public/avatars/:id/:style/:basename.:extension"
  validates_attachment_content_type :icon, :content_type => ['image/jpeg', 'image/png']
  cattr_reader :per_page
  @@per_page = 10	
end

app/controllers/admin/profiles_controller.rb
class Admin::ProfilesController < ApplicationController
   layout "admin"
   before_filter :authenticate_user!
  # GET /profiles
  # GET /profiles.xml
  def index
  	@users = User.all
  	page = params[:page] || 1 
    #@profiles = Profile.all
    @profiles = Profile.paginate :page => page, :order => 'created_at DESC'
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.xml
  def show
  	@user = current_user
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.xml
  def new
  	@user = current_user
    #@profile = Profile.new
    @profile = @user.build_profile
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
  	@user = current_user
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.xml
  def create
  	@user = current_user
    @profile = Profile.new(params[:profile])
    #@profile = @user.create_profile(params[:profile])
    respond_to do |format|
      if @profile.save
        format.html { redirect_to([:admin,@profile], :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.xml
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to([:admin,@profile], :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.xml
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(admin_profiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_filter :authenticate_user!
  # GET /profiles
  # GET /profiles.xml
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.xml
  def show
  	@user = current_user
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.xml
  def new
  	@user = current_user
    #@profile = Profile.new
    @profile = @user.build_profile
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
  	@user = current_user
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.xml
  def create
  	@user = current_user
    #@profile = Profile.new(params[:profile])
    @profile = @user.create_profile(params[:profile])
    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.xml
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(@profile, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.xml
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(profiles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/profiles_helper.rb
module Admin::ProfilesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/profiles/_form.html.erb
  <div class="group">
    <%= f.label :user_id, t("activerecord.attributes.profile.user_id", :default => "User"), :class => :label %>
    <%= f.text_field :user_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :company_id, t("activerecord.attributes.profile.company_id", :default => "Company"), :class => :label %>
    <%= f.text_field :company_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :name, t("activerecord.attributes.profile.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :surname, t("activerecord.attributes.profile.surname", :default => "Surname"), :class => :label %>
    <%= f.text_field :surname, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :position, t("activerecord.attributes.profile.position", :default => "Position"), :class => :label %>
    <%= f.text_field :position, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :telephone, t("activerecord.attributes.profile.telephone", :default => "Telephone"), :class => :label %>
    <%= f.text_field :telephone, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :mobile, t("activerecord.attributes.profile.mobile", :default => "Mobile"), :class => :label %>
    <%= f.text_field :mobile, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :email, t("activerecord.attributes.profile.email", :default => "Email"), :class => :label %>
    <%= f.text_field :email, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <label class="label">Avatar</label>
    <%= f.file_field :avatar, :class => 'text_field' %>
    <span class="description">upload avatar 120x120</span>
  </div>

        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
  <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + " " + t("web-app-theme.cancel", :default => "Cancel"), admin_profiles_path, :class => "button" %> 
</div>

app/views/admin/profiles/_sidebar.html.erb
<div class="block">
  <h3>Document Categories</h3>
  <ul class="navigation">
    <li><a href="<%= admin_languages_path %>">Languages</a></li>
    <li><a href="<%= admin_pages_path %>">Pages</a></li>
    <li><a href="<%= admin_stations_path %>">Stations</a></li>
    <li><a href="<%= admin_tasks_path %>">Tasks</a></li>
    <li><a href="<%= admin_announces_path %>">Announces</a></li>
    <li><a href="<%= admin_events_path %>">Events</a></li>
    <li><a href="<%= admin_newsletters_path %>">Newletters</a></li> 
    <li><a href="<%= admin_reports_path %>">Reports</a></li> 
  </ul>

  
  <h3>Document Types</h3>
  <ul class="navigation">
    <li><a href="<%= admin_categories_path %>">Categories</a></li>
    <li><a href="<%= admin_events_types_path %>">EventsTypes</a></li>
    <li><a href="<%= admin_newsletters_types_path %>">NewlettersTypes</a></li>  
    <li><a href="<%= admin_reports_types_path %>">ReportsTypes</a></li>  
  </ul>

  <h3>User Management (only Admin)</h3>
  <ul class="navigation">
    <li><a href="<%= admin_users_path %>">User</a></li>
    <li><a href="<%= admin_profiles_path %>">Profile</a></li>
    <li><a href="<%= admin_roles_path %>">Roles Base Authentication</a></li>    
  </ul>
</div>


<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>

app/views/admin/profiles/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_profiles_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_profile_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_profile_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Profile</h2>
    <div class="inner">
      <%= form_for @profile, :url => admin_profile_path(@profile), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/profiles/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_profiles_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_profile_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Profiles</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
           <th>
            <%= t("activerecord.attributes.admin_profile.user_id", :default => t("activerecord.labels.user_id", :default => "User_id")) %>
          </th>
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @profiles.each do |profile| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= profile.id %>
          </td>
          <td>
            <%= link_to profile.user_id, admin_profile_path(profile) %>
          </td>
                    <td>
            <%= profile.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_profile_path(profile) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_profile_path(profile) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_profile_path(profile), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @profiles  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/profiles/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_profiles_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_profile_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Profile</h2>
    <div class="inner">
      <%= form_for :profile, :url => admin_profiles_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/profiles/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_profiles_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_profile_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_profile_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_profile.user_id", :default => t("activerecord.labels.user_id", :default => "User")) %>:</b>
          <%= @profile.user_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_profile.company_id", :default => t("activerecord.labels.company_id", :default => "Company")) %>:</b>
          <%= @profile.company_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_profile.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @profile.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_profile.surname", :default => t("activerecord.labels.surname", :default => "Surname")) %>:</b>
          <%= @profile.surname %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_profile.position", :default => t("activerecord.labels.position", :default => "Position")) %>:</b>
          <%= @profile.position %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_profile.telephone", :default => t("activerecord.labels.telephone", :default => "Telephone")) %>:</b>
          <%= @profile.telephone %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_profile.mobile", :default => t("activerecord.labels.mobile", :default => "Mobile")) %>:</b>
          <%= @profile.mobile %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_profile.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</b>
          <%= @profile.email %>
        </p>

       <p>
       32x32<%= image_tag @profile.avatar.url(:iconsmall)%>&nbsp;&nbsp;
       48x48<%= image_tag @profile.avatar.url(:small)%>&nbsp;&nbsp;
       85x85<%= image_tag @profile.avatar.url(:normal)%>&nbsp;&nbsp;
       <%= image_tag @profile.avatar.url()%><br/>
       
       </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_profile_path(@profile), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_profile_path(@profile), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>