config/routes.rb
Purpleline::Application.routes.draw do


  resources :reports

  #get "static_maps/map"

  #get "static_pages/page"
  resources :members
  devise_for :users, :path_names => {:sign_up => "register"}
namespace :admin do
  resources :purple_assets
  resources :profiles
  resources :roles
  resources :newsletters_translations
  resources :categories
  resources :newsletters_types
  resources :newsletters  do resources :purple_assets end
  resources :events_translations
  resources :events_types
  resources :events do resources :purple_assets end
  resources :pages_translations
  resources :pages
  resources :languages
  resources :announces_types  
  resources :announces do resources :purple_assets end
  resources :announces_translations
  resources :tasks
  resources :tasks_translations
  resources :stations do resources :purple_assets end
  resources :stations_translations  
  resources :progresses
  resources :users
  resources :reports
  resources :reports_translations
  resources :reports_types
end

  root :to => "home#index",:lang=>"th"
  get   "/home/allannounce"
  get   "home/lasttenannounce"
  get   "home/monthlyannounce"
  get   "/home/allnews"
  get   "/home/lasttennews"
  get   "/home/monthlynews"
  get   "/home/allreport"
  get   "home/latestreport"
  get   "home/monthlyreport"
  get   "/home/allevent"
  get   "home/latestevent"
  get   "home/monthlyevent"
  get   "home/gallery"   
  get   "home/setlang"
  match "/page/:filename.:format" => "static_pages#page"
  match "/map/:mapname/:filename.:format" => "static_maps#map"
  match "/map/:mapname/:z/:x/:y.:format" => "static_maps#maptile"
  match "/allstation" => "home#allstation"
  match "/main" => "home#index"
  match "/mrta" => "home#mrta"
  match "/gallery" => "home#gallery"
  match "/allannounce" =>  "home#allannounce"
  match "/project" => "home#project"
  match "/station/:id" => 'home#station'
  match "/faceboxmap/:id" => 'home#faceboxmap'
  match "/pagetran/:id" => 'home#pagetran'
  match "/pageview/:id" => 'home#pageview'
  match "/mrtaview/:id" => 'home#mrtaview' 
  match "/category/:id" => 'home#category'   
  match "/eventstype/:id" => 'home#eventstype'   
  match "/reportstype/:id" => 'home#reportstype'   
  
  match "/announce/:id" => 'home#announcement' 
  match "/showevent/:id" => 'home#showevent'   
  match "/showreport/:id" => 'home#showreport'   
  match "/shownews/:id" => 'home#shownews'   
  match "/progress" => 'home#progress'
  match "/filterstation/:id" => 'home#filterstation'
  match "/fullmap" => 'home#fullmap'
  match "/admin" => 'admin/pages#index'

end

app/models/pages_translation.rb
class PagesTranslation < ActiveRecord::Base
	cattr_reader :per_page
  @@per_page = 20

end

app/controllers/admin/pages_translations_controller.rb
class Admin::PagesTranslationsController < ApplicationController
	layout  "admin"
  before_filter :authenticate_user!	
  #include ActionView::Helpers::PrototypeHelper
  include ActionView::Helpers::JavaScriptHelper
  include ActionView::Helpers::TagHelper
  # GET /pages_translations
  # GET /pages_translations.xml
  def index
  	page = params[:page] || 1
    @pages_translations = PagesTranslation.paginate :page => page, :order => 'created_at DESC'
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pages_translations }
    end
  end

  # GET /pages_translations/1
  # GET /pages_translations/1.xml
  def show
    @pages_translation = PagesTranslation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pages_translation }
    end
  end

  # GET /pages_translations/new
  # GET /pages_translations/new.xml
  def new
    @pages_translation = PagesTranslation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pages_translation }
    end
  end

  # GET /pages_translations/1/edit
  def edit
    @pages_translation = PagesTranslation.find(params[:id])
  end

  # POST /pages_translations
  # POST /pages_translations.xml
  def create
    @pages_translation = PagesTranslation.new(params[:pages_translation])

    respond_to do |format|
      if @pages_translation.save
        format.html { redirect_to([:admin,@pages_translation], :notice => 'Pages translation was successfully created.') }
        format.xml  { render :xml => @pages_translation, :status => :created, :location => @pages_translation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pages_translation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages_translations/1
  # PUT /pages_translations/1.xml
  def update
    @pages_translation = PagesTranslation.find(params[:id])

    respond_to do |format|
      if @pages_translation.update_attributes(params[:pages_translation])
        format.html { redirect_to([:admin,@pages_translation], :notice => 'Pages translation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pages_translation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages_translations/1
  # DELETE /pages_translations/1.xml
  def destroy
    @pages_translation = PagesTranslation.find(params[:id])
    @pages_translation.destroy

    respond_to do |format|
      format.html { redirect_to(admin_pages_translations_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_translations_controller.rb
class PagesTranslationsController < ApplicationController
  # GET /pages_translations
  # GET /pages_translations.xml
  def index
    @pages_translations = PagesTranslation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pages_translations }
    end
  end

  # GET /pages_translations/1
  # GET /pages_translations/1.xml
  def show
    @pages_translation = PagesTranslation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pages_translation }
    end
  end

  # GET /pages_translations/new
  # GET /pages_translations/new.xml
  def new
    @pages_translation = PagesTranslation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pages_translation }
    end
  end

  # GET /pages_translations/1/edit
  def edit
    @pages_translation = PagesTranslation.find(params[:id])
  end

  # POST /pages_translations
  # POST /pages_translations.xml
  def create
    @pages_translation = PagesTranslation.new(params[:pages_translation])

    respond_to do |format|
      if @pages_translation.save
        format.html { redirect_to(@pages_translation, :notice => 'Pages translation was successfully created.') }
        format.xml  { render :xml => @pages_translation, :status => :created, :location => @pages_translation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pages_translation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pages_translations/1
  # PUT /pages_translations/1.xml
  def update
    @pages_translation = PagesTranslation.find(params[:id])

    respond_to do |format|
      if @pages_translation.update_attributes(params[:pages_translation])
        format.html { redirect_to(@pages_translation, :notice => 'Pages translation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pages_translation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pages_translations/1
  # DELETE /pages_translations/1.xml
  def destroy
    @pages_translation = PagesTranslation.find(params[:id])
    @pages_translation.destroy

    respond_to do |format|
      format.html { redirect_to(pages_translations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/admin/pages_translations_helper.rb
module Admin::PagesTranslationsHelper
end

app/helpers/pages_translation_helper.rb
module PagesTranslationHelper
end

app/helpers/pages_translations_helper.rb
module PagesTranslationsHelper
end

app/views/admin/pages_translations/_form.html.erb
<ol class="formatcol-four">
  <li>
  <div class="group">
    <%= f.label :language_id, t("activerecord.attributes.pages_translation.language_id", :default => "Language"), :class => :label %>
    <%= f.collection_select :language_id,Language.all,:id,:name,{:prompt=>"Select Language"}, {:class => 'text_field',:style=>"width:150px"} %>
  </div>
  </li>
  <li>
  <div class="group">
    <%= f.label :page_id, t("activerecord.attributes.pages_translation.page_id", :default => "Page"), :class => :label %>
    <%= f.collection_select :page_id,Page.all,:id,:name,{:prompt=>"Select Page"}, {:class => 'text_field',:style=>"width:150px"} %>
  </div>
  </li>
</ol>
  <div class="group">
    <%= f.label :title, t("activerecord.attributes.pages_translation.title", :default => "Title"), :class => :label %>
    <%= f.text_field :title, :class => 'text_field' %>
  </div>

  <div class="group">
    <%= f.label :content, t("activerecord.attributes.pages_translation.content", :default => "Content"), :class => :label %>
    <%= f.cktext_area :content, :class => 'text_area' %>
  </div>

<ol class="formatcol-three">
 <li>
  <div class="group">
    <%= f.label :start_on, t("activerecord.attributes.pages_translation.start_on", :default => "Start on"), :class => :label %>
    <%= f.text_field :start_on, {:class => 'text_field',:style=>"width:150px"} %>
  </div>
 </li>
 <li>
  <div class="group">
    <%= f.label :stop_on, t("activerecord.attributes.pages_translation.stop_on", :default => "Stop on"), :class => :label %>
    <%= f.text_field :stop_on, {:class => 'text_field',:style=>"width:150px"} %>
  </div>
 </li>
 <li>
  <div class="group">
    <%= f.label :publish, t("activerecord.attributes.pages_translation.publish", :default => "Publish"), :class => :label %>
    <%= f.check_box :publish, :class => 'check_box' %>
  </div>
 </li>
</ol>
  <div class="group">
    <%= f.label :user_id, t("activerecord.attributes.pages_translation.user_id", :default => "User"), :class => :label %>
    <%= f.text_field :user_id, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
  <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + " " + t("web-app-theme.cancel", :default => "Cancel"), admin_pages_translations_path, :class => "button" %> 
</div>

app/views/admin/pages_translations/_sidebar.html.erb
<div class="block">
  <h3>Document Categories</h3>
  <ul class="navigation">
    <li><a href="<%= admin_languages_path %>">Languages</a></li>
    <li><a href="<%= admin_pages_path %>">Pages</a></li>
    <li><a href="<%= admin_stations_path %>">Stations</a></li>
    <li><a href="<%= admin_tasks_path %>">Tasks</a></li>
    <li><a href="<%= admin_announces_path %>">Announces</a></li>
    <li><a href="<%= admin_events_path %>">Events</a></li>
    <li><a href="<%= admin_newsletters_path %>">Newletters</a></li> 
    <li><a href="<%= admin_reports_path %>">Reports</a></li> 
  </ul>

  
  <h3>Document Types</h3>
  <ul class="navigation">
    <li><a href="<%= admin_categories_path %>">Categories</a></li>
    <li><a href="<%= admin_events_types_path %>">EventsTypes</a></li>
    <li><a href="<%= admin_newsletters_types_path %>">NewlettersTypes</a></li>  
    <li><a href="<%= admin_reports_types_path %>">ReportsTypes</a></li>  
  </ul>

  <h3>User Management (only Admin)</h3>
  <ul class="navigation">
    <li><a href="<%= admin_users_path %>">User</a></li>
    <li><a href="<%= admin_profiles_path %>">Profile</a></li>
    <li><a href="<%= admin_roles_path %>">Roles Base Authentication</a></li>    
  </ul>
</div>


<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>

app/views/admin/pages_translations/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_pages_translations_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_pages_translation_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_pages_translation_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> PagesTranslation</h2>
    <div class="inner">
      <%= form_for @pages_translation, :url => admin_pages_translation_path(@pages_translation), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/pages_translations/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_pages_translations_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_pages_translation_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> PagesTranslations</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
          <th>
            <%= t("activerecord.attributes.admin_pages_translation.page_id", :default => t("activerecord.labels.page_id", :default => "Page_id")) %>
          </th>
          <th>
            <%= t("activerecord.attributes.admin_pages_translation.title", :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>          
                    <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">Actions</th>
        </tr>
        <% @pages_translations.each do |pages_translation| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= pages_translation.id %>
          </td>
          <td>
            <%= link_to pages_translation.page_id, admin_page_path(pages_translation.page_id) %>
          </td>
          <td>
            <%=pages_translation.title %>
          </td>          
          <td>
            <%= pages_translation.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_pages_translation_path(pages_translation) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_pages_translation_path(pages_translation) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_pages_translation_path(pages_translation), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
        <%= will_paginate @pages_translations  %>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/pages_translations/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_pages_translations_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_pages_translation_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  PagesTranslation</h2>
    <div class="inner">
      <%= form_for :pages_translation, :url => admin_pages_translations_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/admin/pages_translations/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_pages_translations_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_pages_translation_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_pages_translation_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.admin_pages_translation.page_id", :default => t("activerecord.labels.page_id", :default => "Page")) %>:</b>
          <%= @pages_translation.page_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_pages_translation.language_id", :default => t("activerecord.labels.language_id", :default => "Language")) %>:</b>
          <%= @pages_translation.language_id %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_pages_translation.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @pages_translation.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_pages_translation.content", :default => t("activerecord.labels.content", :default => "Content")) %>:</b>
          <%= @pages_translation.content.html_safe %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_pages_translation.publish", :default => t("activerecord.labels.publish", :default => "Publish")) %>:</b>
          <%= @pages_translation.publish %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_pages_translation.start_on", :default => t("activerecord.labels.start_on", :default => "Start on")) %>:</b>
          <%= @pages_translation.start_on %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_pages_translation.stop_on", :default => t("activerecord.labels.stop_on", :default => "Stop on")) %>:</b>
          <%= @pages_translation.stop_on %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_pages_translation.user_id", :default => t("activerecord.labels.user_id", :default => "User")) %>:</b>
          <%= @pages_translation.user_id %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_pages_translation_path(@pages_translation), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_pages_translation_path(@pages_translation), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>